### ISSUE TITLE
threshold

### ISSUE THREAD

**Issue by jwijffels** [manuelciosici/ExchangeAndBrown#1]
Hello,
I'm inspecting the code in order to be able to maken an R wrapper around this.
I see at code line https://github.com/manuelciosici/ExchangeAndBrown/blob/master/src/src/readers/ReaderThreshold.cpp#L15
that only words which are above the threshold are kept
but https://github.com/manuelciosici/ExchangeAndBrown/blob/master/src/src/readers/ReaderNoOrder.cpp#L53 make sure this pl / pr is always smaller than 1. Shouldn't this be coded as 
`if (corpus.pl[wordID] >= (thresholdVal / corpus.corpusLength)) {`

**Comment by manuelciosici** [comment]
Good catch there. ReaderThreshold is an older class from when I was storing `pl` and `pr` as integers. Its unit test was apparently not updated when I changed the representation of `pl` and `pr`.

I have adjusted the unit test to illustrate the problem and fixed the issue, see [merge commit](https://github.com/manuelciosici/ExchangeAndBrown/commit/4ca0e4dbbe03b3ac6937ac0e5ced85f3a8a9b2b2).

I will close this issue now. Thanks again for spotting the bug.
